### ISSUE TITLE
Nested addon included hook conflict

### ISSUE THREAD

**Issue by nmcclay** [martndemus/ember-font-awesome#109]
I originally noted this bug for [ember-composable-helpers](https://github.com/DockYard/ember-composable-helpers/issues/231) but thought I may be worth asking about here as well.  Basically the addon is very opinionated about how it is invoked as a nested addon.  Example of `index.js` in a default ember addon in 2.7:

```
module.exports = {
  name: 'composable-helpers-font-awesome-addon-test',

  included: function(app, parentAddon) {
    // fails ember-composable-helpers
    // this._super.included(arguments);

    // fails ember-font-awesome
    this._super.included.apply(this, arguments);
  }
};
```

Basically the difference between these two different methods of calling the included hook seem incompatible with each other because of internal differences in the nested addons.  In this case the error surfaces in ember-font-awesome with 'target.bowerDirectory' being undefined:

`var faPath = path.join(target.bowerDirectory, 'font-awesome');`

```
Path must be a string. Received undefined
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at CoreObject.module.exports.included (/Users/nmcclay/git/composible-test/node_modules/ember-font-awesome/index.js:54:23)
    at CoreObject.superWrapper [as included] (/Users/nmcclay/git/composible-test/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:32:18)
    at /Users/nmcclay/git/composible-test/node_modules/ember-cli/lib/models/addon.js:258:34
    at Array.map (native)
    at CoreObject.eachAddonInvoke (/Users/nmcclay/git/composible-test/node_modules/ember-cli/lib/models/addon.js:256:24)
    at CoreObject.extend.included (/Users/nmcclay/git/composible-test/node_modules/ember-cli/lib/models/addon.js:433:10)
    at CoreObject.superWrapper [as included] (/Users/nmcclay/git/composible-test/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:32:18)
    at CoreObject.module.exports.included (/Users/nmcclay/git/composible-test/index.js:12:26)
```

This is super unfortunate because there is clearly no conflict in the underlying domains of these addons, but due to their internals they can't be used together in a nested addon.

**Comment by martndemus** [comment]
This should now be fixed because of the switch to NPM.
