### ISSUE TITLE
Doesn't seem to work when used as a dependency in an addon with 3.0.2

### ISSUE THREAD

**Issue by Soliah** [martndemus/ember-font-awesome#129]
With a fresh `ember addon` on ember-cli 2.11.0, running `ember test` gives a `TypeError: Cannot read property 'forEach' of undefined` at https://github.com/martndemus/ember-font-awesome/blob/master/index.js#L101

```
ember-cli: 2.11.0
node: 6.9.5
os: darwin x64
```

Full stacktrace:

```
TypeError: Cannot read property 'forEach' of undefined
    at Class.included (/Users/Soliah/Code/font-awesome-nested-addon/node_modules/ember-font-awesome/index.js:101:29)
    at Class.superWrapper [as included] (/Users/Soliah/Code/font-awesome-nested-addon/node_modules/core-object/lib/assign-properties.js:32:18)
    at /Users/Soliah/Code/font-awesome-nested-addon/node_modules/ember-cli/lib/models/addon.js:245:34
    at Array.map (native)
    at Class.eachAddonInvoke (/Users/Soliah/Code/font-awesome-nested-addon/node_modules/ember-cli/lib/models/addon.js:243:24)
    at Class.included (/Users/Soliah/Code/font-awesome-nested-addon/node_modules/ember-cli/lib/models/addon.js:420:10)
    at Class.superWrapper [as included] (/Users/Soliah/Code/font-awesome-nested-addon/node_modules/core-object/lib/assign-properties.js:32:18)
    at EmberAddon.<anonymous> (/Users/Soliah/Code/font-awesome-nested-addon/node_modules/ember-cli/lib/broccoli/ember-app.js:492:15)
    at Array.filter (native)
    at EmberAddon.EmberApp._notifyAddonIncluded (/Users/Soliah/Code/font-awesome-nested-addon/node_modules/ember-cli/lib/broccoli/ember-app.js:487:45)
    at EmberAddon.EmberApp [as appConstructor] (/Users/Soliah/Code/font-awesome-nested-addon/node_modules/ember-cli/lib/broccoli/ember-app.js:138:8)
    at new EmberAddon (/Users/Soliah/Code/font-awesome-nested-addon/node_modules/ember-cli/lib/broccoli/ember-addon.js:33:8)
    at module.exports (/Users/Soliah/Code/font-awesome-nested-addon/ember-cli-build.js:6:13)
    at CoreObject.setupBroccoliBuilder (/Users/Soliah/Code/font-awesome-nested-addon/node_modules/ember-cli/lib/models/builder.js:84:19)
    at CoreObject.init (/Users/Soliah/Code/font-awesome-nested-addon/node_modules/ember-cli/lib/models/builder.js:64:10)
    at CoreObject.superWrapper [as init] (/Users/Soliah/Code/font-awesome-nested-addon/node_modules/core-object/lib/assign-properties.js:32:18)
    at CoreObject.Class (/Users/Soliah/Code/font-awesome-nested-addon/node_modules/core-object/core-object.js:32:33)
    at CoreObject.run (/Users/Soliah/Code/font-awesome-nested-addon/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at CoreObject.<anonymous> (/Users/Soliah/Code/font-awesome-nested-addon/node_modules/ember-cli/lib/commands/test.js:164:27)
    at tryCatch (/Users/Soliah/Code/font-awesome-nested-addon/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/Users/Soliah/Code/font-awesome-nested-addon/node_modules/rsvp/dist/rsvp.js:553:13)
    at /Users/Soliah/Code/font-awesome-nested-addon/node_modules/rsvp/dist/rsvp.js:628:16
```

Example repo here: https://github.com/Soliah/font-awesome-nested-addon

**Comment by Soliah** [comment]
Actually I think this is related to #109.

Adding an included hook with the following works.

```
  included: function(app) {
    this._super.included(arguments);
  }
```

**Comment by Soliah** [comment]
I decided it's simpler for me to use peerDependencies until there's better support for n-level deep nesting of addons.
