### ISSUE TITLE
Doesn't work with engines (anymore?)

### ISSUE THREAD

**Issue by buschtoens** [martndemus/ember-font-awesome#132]
#106 indicates that this addon once worked with `ember-engines`, specifically in an `in-repo-engine`.

I've set up a simple demo app that shows that `ember-font-awesome` cannot be consumed in an `in-repo-engine`: [buschtoens/fa-engine-demo](https://github.com/buschtoens/fa-engine-demo)

Running `ember serve` produces the following output:

```
DEPRECATION: foo-engine engine must specify the `lazyLoading` property to `true` or `false` as to whether the engine should be lazily loaded.
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
asset.replace is not a function
TypeError: asset.replace is not a function
    at Class.import (/home/jan/github/fa-engine-demo/node_modules/ember-engines/lib/engine-addon.js:241:17)
    at Class.included (/home/jan/github/fa-engine-demo/node_modules/ember-font-awesome/index.js:98:20)
    at Class.superWrapper [as included] (/home/jan/github/fa-engine-demo/node_modules/core-object/lib/assign-properties.js:32:18)
    at /home/jan/github/fa-engine-demo/node_modules/ember-cli/lib/models/addon.js:245:34
    at Array.map (native)
    at Class.eachAddonInvoke (/home/jan/github/fa-engine-demo/node_modules/ember-cli/lib/models/addon.js:243:24)
    at Class.included (/home/jan/github/fa-engine-demo/node_modules/ember-cli/lib/models/addon.js:420:10)
    at Class.superWrapper [as included] (/home/jan/github/fa-engine-demo/node_modules/core-object/lib/assign-properties.js:32:18)
    at Class.included (/home/jan/github/fa-engine-demo/node_modules/ember-engines/lib/engine-addon.js:263:28)
    at EmberApp.<anonymous> (/home/jan/github/fa-engine-demo/node_modules/ember-cli/lib/broccoli/ember-app.js:492:15)
```

```
ember-font-awesome: 3.0.4
ember-cli: 2.11.1
node: 7.6.0
os: linux x64
```

**Comment by buschtoens** [comment]
Using `ember-font-awesome@2.2.0` you get a different error:

```
Path must be a string. Received undefined
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at Class.included (/home/jan/github/fa-engine-demo/node_modules/ember-font-awesome/index.js:54:23)
    at Class.superWrapper [as included] (/home/jan/github/fa-engine-demo/node_modules/core-object/lib/assign-properties.js:32:18)
    at /home/jan/github/fa-engine-demo/node_modules/ember-cli/lib/models/addon.js:245:34
    at Array.map (native)
    at Class.eachAddonInvoke (/home/jan/github/fa-engine-demo/node_modules/ember-cli/lib/models/addon.js:243:24)
    at Class.included (/home/jan/github/fa-engine-demo/node_modules/ember-cli/lib/models/addon.js:420:10)
    at Class.superWrapper [as included] (/home/jan/github/fa-engine-demo/node_modules/core-object/lib/assign-properties.js:32:18)
    at Class.included (/home/jan/github/fa-engine-demo/node_modules/ember-engines/lib/engine-addon.js:263:28)
```

**Comment by buschtoens** [comment]
https://github.com/ember-engines/ember-engines/issues/343

**Comment by buschtoens** [comment]
Bug will be fixed upstream.
