### ISSUE TITLE
Ember broke after installing ember-font-awesome

### ISSUE THREAD

**Issue by jgomo3** [martndemus/ember-font-awesome#159]
During the installation of the plugin, I get this feedback:

```
$ ember install ember-font-awesome
NPM: Installed ember-font-awesome
Unexpected token {
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/*****/Playground/ember_lab/loppylog/node_modules/ember-font-awesome/index.js:9:27)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

And after that, ember stop working giving the same answer:
```
$ ember --version
Unexpected token {
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/*****/Playground/ember_lab/loppylog/node_modules/ember-font-awesome/index.js:9:27)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

This is just a fresh install following a tutorial. My version of ember is 2.12. And for some reason, the `ember install` command insist on installing the version "^4.0.0-alpha.3" of ember-font-awesome (It shouldn't be installing an alpha version).

**Comment by jrjohnson** [comment]
@jgomo3 thanks for the report we will look into what's going on with the v4 alpha in a new app.
I'm not sure why `ember install` is giving you a bad version either but you can install the release version with `ember install ember-font-awesome@^3.0.5` which will hopefully get you up and running.

**Comment by jrjohnson** [comment]
`ember install ember-font-awesome` is currently picking up the alpha versions because of the way NPM calculates tags. When you publish it picks up the `latest` tag automatically. Instead they should be published with `npm publish --tag alpha`. CC @cibernox @buschtoens 

ref: https://medium.com/@mbostock/prereleases-and-npm-e778fc5e2420

**Comment by cibernox** [comment]
@jgomo3 The error makes me think that you are using node v4. Is that the case? Can you check if updating to node 6 fixes the error.

It is a known issue that the latest version of the addon requires node6. There is no particular reason why this have to be this way, it is mostly because the approach being developed there is quite new and compatibility with older nodes was not a priority. 

But I intend to make it work in node 4 at some point in the next weeks.

**Comment by jgomo3** [comment]
@cibernox Yes, indeed it is npm 4.

**Comment by cibernox** [comment]
@jgomo3 you mean *node* 4? The version of npm should be irrelevant.

**Comment by jgomo3** [comment]
Yes, sorry. Node 4.

**Comment by cibernox** [comment]
Good. Can you now confirm if in node 6 it does work. If it does, we can close this as "Known issue but will address soon".

**Comment by jgomo3** [comment]
It works with Node 6.

This is a "Know issue".

**Comment by samselikoff** [comment]
I hit this and it was very hard to debug.

Any insight on the level of effort required to get it to work w/node 4? Since Ember CLI will support Node 4 until end of March next year, others may run into this.

**Comment by Turbo87** [comment]
FWIW it seems like the only thing needed to support Node 4 is to avoid destructuring. Everything else should work just fine.
