### ISSUE TITLE
Can't use in Ember Engine

### ISSUE THREAD

**Issue by dpatz** [martndemus/ember-font-awesome#176]
Whenever I add font awesome as a dependency inside my engine, I get the following error:
```Funnel (Funnel
    vendor/font-awesome/fonts
    /fonts
   include:6): Expected Broccoli node, got undefined for inputNodes[0]
TypeError: Funnel (Funnel
    vendor/font-awesome/fonts
    /fonts
   include:6): Expected Broccoli node, got undefined for inputNodes[0]
    at Funnel.Plugin (<app-root>/node_modules/broccoli-plugin/index.js:23:13)
    at new Funnel (<app-root>/node_modules/broccoli-funnel/index.js:58:10)
    at funnelReducer.map.options (<app-root>/node_modules/ember-cli/lib/broccoli/ember-app.js:1494:14)
    at Array.map (native)
    at Class.otherAssets (<app-root>/node_modules/ember-cli/lib/broccoli/ember-app.js:1488:63)
    at Class.treeForPublic (<app-root>/node_modules/ember-engines/lib/engine-addon.js:905:30)
    at Class._treeFor (<app-root>/node_modules/ember-cli/lib/models/addon.js:551:33)
    at Class.treeFor (<app-root>/node_modules/ember-engines/lib/engine-addon.js:1119:23)
    at project.addons.map.addon (<app-root>/node_modules/ember-cli/lib/broccoli/ember-app.js:557:22)
    at Array.map (native)
```

Any suggestions?

**Comment by cibernox** [comment]
@dpatz can you confirm what version are you using?

**Comment by dpatz** [comment]
@cibernox I'm using: `ember-font-awesome 4.0.0-alpha.10` with `ember-engines 0.5.11` on `ember 2.14.1`

**Comment by cibernox** [comment]
I'll investigate it. Since now the addon contains an AST transform it is possible that we need to register it for every engine.

**Comment by dpatz** [comment]
Awesome, thanks!

**Comment by donaldwasserman** [comment]
For what it's worth, I tried upgrading to`ember-font-awesome 4.0.0-alpha.10` along with engines 0.5.11 and ember 2.14.1. My app is building fine, but resultings in `Error: Compile Error: fa-icon is not a helper`
