### ISSUE TITLE
Cannot read property 'fontFormats' of undefined on ember engine build 

### ISSUE THREAD

**Issue by nambi** [martndemus/ember-font-awesome#179]
Using ember-font-awesome : 3.0.5 along with ember-cli 2.14.2 and ember-engine 0.5.10. 

Cannot read property 'fontFormats' of undefined
TypeError: Cannot read property 'fontFormats' of undefined
    at Class.treeForVendor (C:\my-addon\node_modules\ember-font-awesome\index.js:16:44)
    at Class._treeFor (C:\my-addon\node_modules\ember-cli\lib\models\addon.js:551:33)
    at Class.treeFor (C:\my-addon\node_modules\ember-cli\lib\models\addon.js:511:21)
    at addons.map.addon (C:\my-addon\node_modules\ember-cli\lib\models\addon.js:383:34)
    at Array.map (native)
    at Class.eachAddonInvoke (C:\my-addon\node_modules\ember-cli\lib\models\addon.js:381:24)
    at Class.treeFor (C:\my-addon\node_modules\ember-engines\lib\engine-addon.js:945:22)
    at project.addons.map.addon (C:\my-addon\node_modules\ember-cli\lib\broccoli\ember-app.js:557:22)
    at Array.map (native)
    at EmberAddon.addonTreesFor (C:\my-addon\node_modules\ember-cli\lib\broccoli\ember-app.js:555:32)

**Comment by jrjohnson** [comment]
@nambi I'm not sure if ember-engines is involved in this issue, my experience with it is limited. Is the addon inside the engine?

Do you have a `'ember-font-awesome'` section in your `ember-cli-build.js`? Can you add that?

**Comment by nambi** [comment]
addon is inside the engine. also we have emberFontAwesome: { } inside ember-cli-build
